# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Capacity.proto

require 'google/protobuf'


descriptor_data = "\n\x0e\x43\x61pacity.proto\x12\x0f\x63om.hasup.proto\"G\n\x08\x43\x61pacity\x12\x11\n\tserver_id\x18\x01 \x01(\x05\x12\x15\n\rserver_status\x18\x02 \x01(\x05\x12\x11\n\ttimestamp\x18\x03 \x01(\x03\"$\n\x0f\x43\x61pacityRequest\x12\x11\n\tserver_id\x18\x01 \x01(\x05\"A\n\x10\x43\x61pacityResponse\x12-\n\ncapacities\x18\x01 \x03(\x0b\x32\x19.com.hasup.proto.CapacityB(\n\x0f\x63om.hasup.protoB\rCapacityProto\xea\x02\x05Hasupb\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Hasup
  Capacity = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.hasup.proto.Capacity").msgclass
  CapacityRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.hasup.proto.CapacityRequest").msgclass
  CapacityResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.hasup.proto.CapacityResponse").msgclass
end
