# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Message.proto

require 'google/protobuf'


descriptor_data = "\n\rMessage.proto\x12\x0f\x63om.hasup.proto\"\x8c\x01\n\x07Message\x12\x0e\n\x06\x64\x65mand\x18\x01 \x01(\t\x12\x33\n\x08response\x18\x02 \x01(\x0e\x32!.com.hasup.proto.Message.Response\x12\x11\n\ttimestamp\x18\x03 \x01(\x03\")\n\x08Response\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x07\n\x03YEP\x10\x01\x12\x07\n\x03NOP\x10\x02\x42\'\n\x0f\x63om.hasup.protoB\x0cMessageProto\xea\x02\x05Hasupb\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Hasup
  Message = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.hasup.proto.Message").msgclass
  Message::Response = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.hasup.proto.Message.Response").enummodule
end
