# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Subscriber.proto

require 'google/protobuf'


descriptor_data = "\n\x10Subscriber.proto\x12\x0f\x63om.hasup.proto\"\x82\x01\n\nSubscriber\x12\'\n\x06status\x18\x01 \x01(\x0e\x32\x17.com.hasup.proto.Status\x12\n\n\x02id\x18\x02 \x01(\x05\x12\x14\n\x0cname_surname\x18\x03 \x01(\t\x12\x12\n\nstart_date\x18\x04 \x01(\x03\x12\x15\n\rlast_accessed\x18\x05 \x01(\x03*<\n\x06Status\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x08\n\x04SUBS\x10\x01\x12\x08\n\x04ONLN\x10\x02\x12\x08\n\x04OFFL\x10\x03\x12\x07\n\x03\x44\x45L\x10\x04\x42*\n\x0f\x63om.hasup.protoB\x0fSubscriberProto\xea\x02\x05Hasupb\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Hasup
  Subscriber = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.hasup.proto.Subscriber").msgclass
  Status = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.hasup.proto.Status").enummodule
end
